spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conexa?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: usersecretforjwtauthenticateusersecretforjwtauthenticateusersecretforjwtauthenticateuse