spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conexa?createDatabaseIfNotExist=true
    username: root
    password: password
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: mysecretkey